### ISSUE TITLE
App Store Rejection.  ITMS-91064: Invalid tracking information

### ISSUE THREAD

**Issue by operatordevelopment** [vmwareairwatchsdk/iOS-WorkspaceONE-SDK#7]
Getting auto-rejected by the Apple App Store during submission for review.
I tried both iOS-WorkspaceONE-SDK version 24.6.0 and 24.7.0 (these are how the version numbers display via SPM).
Here is the full message I get from the App Store:

Please correct the following issues and upload a new binary to App Store Connect.

ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/AWSDK.framework/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn‘t empty. Keys and values in your app’s privacy manifest must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

Apple Developer Relations

I checked the PrivacyInfo.xcprivacy and I can see that the App Store is correct.  Tracking is turned off.  But there is an empty item in the NSPrivacyTrackingDomains array, causing the failure.

I tried manually changing each of the PrivacyInfo.xcprivacy plists but then the build fails the signature check... which makes sense.  Hey.  I wanted to try *something*.

What's the solution for this?  I need to get my app submitted to the App Store.

Much thanks in advance for the help!  Hoping it's a small change needed and ideally something I can just do on my own.

**Comment by operatordevelopment** [comment]
Issue was introduced in 24.4.0.  Not getting an app store auto-rejection with 24.1.0.

**Comment by operatordevelopment** [comment]
Here is a marked up version of the Privacy file, showing what's wrong with it, at least from the auto-rejection the Apple App Store is doing.
[PrivacyInfo24_4_0.pdf](https://github.com/user-attachments/files/16615451/PrivacyInfo24_4_0.pdf)

**Comment by chaitu-venky** [comment]
@operatordevelopment Thanks for raising the issue. Currently the issue is resolved and republished the Framework/Package. Clear the package caches and re-clone them.

**Comment by operatordevelopment** [comment]
Thank you!
